# frozen_string_literal: true
# This file isn't named "Dangerfile" so that it's not imported by default since it's only meant to be run in the `integration:performance` job.

comment = File.read('./tmp/performance.md')

unless comment.strip.empty?
  markdown(<<~MARKDOWN)
    #{comment}
  MARKDOWN
end
