#!/usr/bin/env ruby
#
# frozen_string_literal: true

require_relative '../lib/kdk'

system(*%w[kdk start postgresql])

postgresql = KDK::Postgresql.new
abort 'postgres not ready' unless postgresql.ready?

abort 'createdb failed' unless postgresql.createdb('grafana')
